Repository euclid-lyc/lyc-backend, pull requests merged in 2024-12, with the labels that each got.

#87 [feat] Implement Collage APIs
  lyc-spring/build.gradle
  lyc-spring/src/main/java/euclid/lyc_spring/apiPayload/code/status/SuccessStatus.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/CollageController.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/collage/CollageCommandService.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/collage/CollageCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/s3/S3ImageService.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/s3/S3ImageServiceImpl.java
Labels: 🌟 Feat

#88 [75]날씨 api 수정본.진짜최종
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/WeatherService.java
Labels: ✏️ Modify

#89 [ FIX] Add Block Member Handling
  lyc-spring/src/main/java/euclid/lyc_spring/controller/ChatController.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/SocialController.java
  lyc-spring/src/main/java/euclid/lyc_spring/domain/BlockMember.java
  lyc-spring/src/main/java/euclid/lyc_spring/domain/Member.java
  lyc-spring/src/main/java/euclid/lyc_spring/dto/request/CommissionRequestDTO.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/BlockMemberRepository.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/PostingRepositoryCustom.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/impl/MessageRepositoryCustomImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/impl/PostingRepositoryCustomImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/chat/ChatQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/commission/CommissionCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/posting/PostingQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/SocialCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/SocialQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/WeatherService.java
Labels: 🛠️ Fix

#90 [DEPLOY] Deploy New Version
  lyc-spring/build.gradle
  lyc-spring/src/main/java/euclid/lyc_spring/apiPayload/code/status/SuccessStatus.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/ChatController.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/CollageController.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/SocialController.java
  lyc-spring/src/main/java/euclid/lyc_spring/domain/BlockMember.java
  lyc-spring/src/main/java/euclid/lyc_spring/domain/Member.java
  lyc-spring/src/main/java/euclid/lyc_spring/dto/request/CommissionRequestDTO.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/BlockMemberRepository.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/PostingRepositoryCustom.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/impl/MessageRepositoryCustomImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/impl/PostingRepositoryCustomImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/chat/ChatQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/collage/CollageCommandService.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/collage/CollageCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/commission/CommissionCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/posting/PostingQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/s3/S3ImageService.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/s3/S3ImageServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/SocialCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/SocialQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/WeatherService.java
Labels: ✈️ Deploy
