Repository euclid-lyc/lyc-backend, pull requests merged in 2024-11, with the labels that each got.

#79 [fix] Fix Dependencies and Build Error
  lyc-spring/build.gradle
  lyc-spring/src/main/java/euclid/lyc_spring/controller/PostingController.java
Labels: 🛠️ Fix

#80 [DEPLOY] Deploy New Version
  lyc-spring/build.gradle
  lyc-spring/src/main/java/euclid/lyc_spring/controller/CommissionController.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/PostingController.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/WeatherController.java
  lyc-spring/src/main/java/euclid/lyc_spring/converter/GridConverter.java
  lyc-spring/src/main/java/euclid/lyc_spring/dto/response/ChatResponseDTO.java
  lyc-spring/src/main/java/euclid/lyc_spring/dto/response/WeatherResponse.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/impl/PostingRepositoryCustomImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/chat/ChatCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/chat/ChatQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/WeatherService.java
Labels: ✈️ Deploy

#82 [Modify] commission code
  lyc-spring/src/main/java/euclid/lyc_spring/apiPayload/code/status/ErrorStatus.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/CommissionController.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/PostingController.java
  lyc-spring/src/main/java/euclid/lyc_spring/controller/SearchController.java
  lyc-spring/src/main/java/euclid/lyc_spring/domain/chat/Chat.java
  lyc-spring/src/main/java/euclid/lyc_spring/domain/chat/Message.java
  lyc-spring/src/main/java/euclid/lyc_spring/domain/chat/commission/CommissionOther.java
  lyc-spring/src/main/java/euclid/lyc_spring/domain/enums/MessageCategory.java
  lyc-spring/src/main/java/euclid/lyc_spring/dto/request/InfoRequestDTO.java
  lyc-spring/src/main/java/euclid/lyc_spring/dto/response/ChatResponseDTO.java
  lyc-spring/src/main/java/euclid/lyc_spring/dto/response/PostingDTO.java
  lyc-spring/src/main/java/euclid/lyc_spring/dto/response/WeatherDTO.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/ChatRepository.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/ChatRepositoryCustom.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/MemberRepositoryCustom.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/impl/ChatRepositoryCustomImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/repository/querydsl/impl/MemberRepositoryCustomImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/chat/ChatCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/chat/ChatQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/commission/CommissionCommandService.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/commission/CommissionCommandServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/commission/CommissionQueryService.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/commission/CommissionQueryServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/search/SearchService.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/search/SearchServiceImpl.java
  lyc-spring/src/main/java/euclid/lyc_spring/service/social/WeatherService.java
Labels: ✏️ Modify
